version: '3.3'

services:
  db:
    image: gastonnicora/deu_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tpdeu
      MYSQL_PASSWORD: tpdeu
      MYSQL_DATABASE: tpdeu  
  api:
    image: blancofrancisco/backend_laboratorio2022
    restart: always
    links:
      - db
    ports:
      - "8080:4000"
      - "80:80"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
    ports:
      - 90:80
